---
title: "logCFU/g na revalidação"
author: "Eduardo de Freitas Costa"
date: "Dezembro 19, 2018"
output: 
  html_document:
    toc: true
    toc_float: true
    toc_depth: 5
    theme: flatly
---

```{r carregando pacotes} 
library(readxl)
library(BRugs)
library(coda)
```


```{r carregando dados}
setwd("N:/Projeto_Eduardo/Gabriela")
sal <- read_excel("bayes_1.xlsx")
View(sal)
```


```{r dados }
dados = list(d=array(cbind(sal$d[1:23],sal$d[24:46]),dim=c(23,2)), Y = array(cbind(sal$placa1, sal$placa2), dim=c(23,2,2)))
dados

```


```{r modelo}
modelo = function(){
  for(i in 1:23){
    for(j in 1:2){
      for(k in 1:2){
       Y[i,j,k] ~ dpois(D[i,j])
      }
      D[i,j]<-E[i]*d[i,j] 
    }
    E[i]<-N[i]*f
    N[i]~dgamma(5,G[i,1])
    G[i,1]<-0.05*d[i,1]
  }
  f<-1/10
  
   
}
```

```{r iniciais e parametros}
inits <- function(){
  N=rep(5,23)
  parameters1 <- "N"
   
}



```


```{r simulação}

simul_sal <- BRugsFit(modelo, dados, inits, numChains = 1, parameters1,
                             nBurnin = 100, nIter=1000, nThin=5, coda=T)
```


```{r resultados e diagnósticos}
plot(simul_sal)
effectiveSize(simul_sal)
autocorr.diag(simul_sal)
summary(simul_sal)

```

```{r}
alfa<-numeric()
for(i in 1:23){
alfa[i]=(sum(gama[i,2:5]))
}



CFU1<-rgamma(10000,shape=alfa[1]+5,scale=20/21)
CFU2<-rgamma(10000,shape=alfa[2]+5,scale=20/21)
CFU3<-rgamma(10000,shape=alfa[3]+5,scale=20/21)
CFU4<-rgamma(10000,shape=alfa[4]+5,scale=20/21)
CFU5<-rgamma(10000,shape=alfa[5]+5,scale=20/21)
CFU6<-rgamma(10000,shape=alfa[6]+5,scale=20/21)
CFU7<-rgamma(10000,shape=alfa[7]+5,scale=20/21)
CFU8<-rgamma(10000,shape=alfa[8]+5,scale=20/21)
CFU9<-rgamma(10000,shape=alfa[9]+5,scale=20/21)
CFU10<-rgamma(10000,shape=alfa[10]+5,scale=20/21)
CFU11<-rgamma(10000,shape=alfa[11]+5,scale=20/21)
CFU12<-rgamma(10000,shape=alfa[12]+5,scale=20/21)
CFU13<-rgamma(10000,shape=alfa[13]+5,scale=20/21)
CFU14<-rgamma(10000,shape=alfa[14]+5,scale=20/21)
CFU15<-rgamma(10000,shape=alfa[15]+5,scale=20/21)
CFU16<-rgamma(10000,shape=alfa[16]+5,scale=20/21)
CFU17<-rgamma(10000,shape=alfa[17]+5,scale=20/21)
CFU18<-rgamma(10000,shape=alfa[18]+5,scale=20/21)
CFU19<-rgamma(10000,shape=alfa[19]+5,scale=20/21)
CFU20<-rgamma(10000,shape=alfa[20]+5,scale=20/21)
CFU21<-rgamma(10000,shape=alfa[21]+5,scale=20/21)
CFU22<-rgamma(10000,shape=alfa[22]+5,scale=20/21)
CFU23<-rgamma(10000,shape=alfa[23]+5,scale=20/21)



log_CFU<-rbind(log(quantile(CFU1,c(0.025,0.5,0.975)),10),
log(quantile(CFU2,c(0.025,0.5,0.975)),10),
log(quantile(CFU3,c(0.025,0.5,0.975)),10),
log(quantile(CFU4,c(0.025,0.5,0.975)),10),
log(quantile(CFU5,c(0.025,0.5,0.975)),10),
log(quantile(CFU6,c(0.025,0.5,0.975)),10),
log(quantile(CFU7,c(0.025,0.5,0.975)),10),
log(quantile(CFU8,c(0.025,0.5,0.975)),10),
log(quantile(CFU9,c(0.025,0.5,0.975)),10),
log(quantile(CFU10,c(0.025,0.5,0.975)),10),
log(quantile(CFU11,c(0.025,0.5,0.975)),10),
log(quantile(CFU12,c(0.025,0.5,0.975)),10),
log(quantile(CFU13,c(0.025,0.5,0.975)),10),
log(quantile(CFU14,c(0.025,0.5,0.975)),10),
log(quantile(CFU15,c(0.025,0.5,0.975)),10),
log(quantile(CFU16,c(0.025,0.5,0.975)),10),
log(quantile(CFU17,c(0.025,0.5,0.975)),10),
log(quantile(CFU18,c(0.025,0.5,0.975)),10),
log(quantile(CFU19,c(0.025,0.5,0.975)),10),
log(quantile(CFU20,c(0.025,0.5,0.975)),10),
log(quantile(CFU21,c(0.025,0.5,0.975)),10),
log(quantile(CFU22,c(0.025,0.5,0.975)),10),
log(quantile(CFU23,c(0.025,0.5,0.975)),10))

write.csv(log_CFU,'bayes_outpút.csv',sep=",")
```

