---
title: "logCFU/g na base"
author: "Eduardo de Freitas Costa"
date: "Dezembro 19, 2018"
output: 
  html_document:
    toc: true
    toc_float: true
    toc_depth: 5
    theme: flatly
---

```{r carregando pacotes} 
library(readxl)
library(BRugs)
library(coda)
```


```{r carregando dados}
setwd("N:/Projeto_Eduardo/Gabriela")
sal <- read_excel("bayes2.xlsx")
View(sal)
```


```{r dados }
dados = list(d=array(cbind(sal$d[1:23],sal$d[24:46]),dim=c(23,2)), Y = array(cbind(sal$placa1, sal$placa2), dim=c(23,2,2)))
dados

```


```{r modelo}
modelo = function(){
  for(i in 1:23){
    for(j in 1:2){
      for(k in 1:2){
       Y[i,j,k] ~ dpois(D[i,j])
      }
      D[i,j]<-E[i]*d[i,j] 
    }
    E[i]<-N[i]*f
    N[i]~dgamma(5,G[i,1])
    G[i,1]<-0.05*d[i,1]
  }
  f<-1/10
  
   
}
```

```{r iniciais e parametros}
inits <- function(){
  N=rep(50000,23)
  parameters1 <- "N"
   
}



```


```{r simulação}

simul_sal <- BRugsFit(modelo, dados, inits, numChains = 1, parameters1,
                             nBurnin = 100, nIter=100000, nThin=20, coda=T)
```


```{r resultados e diagnósticos}
plot(simul_sal)
effectiveSize(simul_sal)
autocorr.diag(simul_sal)
summary(simul_sal)

```

```{r}
write.csv(log(summary(simul_sal)$quantiles,10),file='bayes_output')
```

